// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gogaeva/architecture-lab-3/server/forums"
)

// Injectors from modules.go:

// ComposeApiServer will create an instance of CharApiServer according to providers defined in this file.
func ComposeApiServer(port HttpPortNumber) (*ForumApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	dbInterface := forums.NewDBInterface(db)
	httpListForumsHandlerFunc := forums.HttpListForumsHandler(dbInterface)
	httpAddUserHandlerFunc := forums.HttpAddUserHandler(dbInterface)
	forumApiServer := &ForumApiServer{
		Port:              port,
		ListForumsHandler: httpListForumsHandlerFunc,
		AddUserHandler:    httpAddUserHandlerFunc,
	}
	return forumApiServer, nil
}
